model:
  type: abs_ae
  model_name: abs_ae
  model_kwargs:

data_path: ./test

seed: 42
model_dir: ./artifacts/abs_ae-b_2-lr_3e04/epoch_2999
batch_size: 64
output_filename: ./artifacts/abs_ae-b_2-lr_3e04/epoch_2999/abs_ae-b_2-lr_3e04.pdf
b: 2