model:
  type: ddulaev_ae
  model_name: ddulaev_ae
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 64
  epochs: 1000
  learning_rate: 3.0e-03
  eval_epochs: 300
  output_dir: ./artifacts
  run_name: ddulaev_ae-b_2-1000_epochs-lr_3e04
  b_t: 2